# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift 
osx_image: xcode9 
xcode_workspace: mm_phonenumber_swift.xcworkspace 
xcode_scheme: mm_phonenumber_swift-Example
xcode_sdk: iphonesimulator11.0

script:
- pod lib lin
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/mm_phonenumber_swift.xcworkspace -scheme mm_phonenumber_swift-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
